---

- name: Downloading the Palantir WEF Configuration
  win_shell: ".\\download_palantir_wef.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: palantir_wef
  failed_when: "'Exception' in palantir_wef.stdout"

- debug: msg="{{ palantir_wef.stdout_lines }}"
  
- name: Installing SysInternals Tools
  win_shell: ".\\install-sysinternals.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: sysinternals
  failed_when: "'Exception' in sysinternals.stdout"

- debug: msg="{{ sysinternals.stdout_lines }}"

- name: Installing Velociraptor
  win_shell: ".\\install-velociraptor.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: velociraptor
  failed_when: "'Exception' in velociraptor.stdout"

- debug: msg="{{ velociraptor.stdout_lines }}"

- name: Installing osquery
  win_shell: ".\\install-osquery.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: osquery
  failed_when: "'Exception' in osquery.stdout"

- debug: msg="{{ osquery.stdout_lines }}"

- name: Installing AutorunsToWineventlog
  win_shell: ".\\install-autorunstowineventlog.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: autorunstowineventlog
  failed_when: "'Exception' in autorunstowineventlog.stdout"

- debug: msg="{{ autorunstowineventlog.stdout_lines }}"

- name: refresh the local GPO to ensure we have the latest certs
  win_command: gpupdate /force /boot
  tags:
    - gpupdate

- name: Reboot Server
  win_reboot:
    msg: "Rebooting..."
    pre_reboot_delay: 10
    reboot_timeout: 600
    post_reboot_delay: 60
  tags:
    - reboot

- name: cleanup
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - 'C:\DetectionLab'
    - 'C:\vagrant'
  tags:
    - cleanup

  #- name: Install Utilities 
  #  win_chocolatey:
  #    name:
  #    - NotepadPlusPlus
  #    - GoogleChrome
  #    - WinRar
  #    - wireshark
  #    - winpcap
  #    state: present
  #    ignore_checksums: yes



