---
- name: install choco
  win_copy:
    src: choco.zip
    dest: c:\

- name: install choco2
  win_shell: "Expand-Archive -Path C:\\choco.zip -DestinationPath C:\\windows\\temp -Force"
  
- name: install choco3
  win_shell: .\\chocolateyInstall.ps1
  args:
    chdir: 'C:\windows\temp\choco\'

- name: Install git
  win_chocolatey:
    name: git.install
    state: present
    source: '\\dc.windomain.local\choco'

- name: Check if existing DetectionLab directory
  win_stat:
    path: 'c:\DetectionLab'
  register: dir

- name: Git clone Detectionlab
  win_shell: git clone https://github.com/EuanKerr/DetectionLab.git
  args:
    chdir: 'c:\'
  when: not dir.stat.exists

- name: Git pull Detectionlab
  win_shell: git pull
  args:
    chdir: 'c:\DetectionLab'
  when: dir.stat.exists

- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Force -Recurse c:\DetectionLab\Vagrant c:\vagrant

- name: Join the Domain
  win_shell: .\\provision.ps1
  args:
    chdir: 'c:\vagrant\scripts'

- name: Update group policy
  win_shell: "gpupdate /force"

- name: Reboot Server
  win_reboot:
    msg: "Joined the domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60

- name: Clear Event Logs
  win_shell: "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"

- name: Install classic-shell with chocolatey
  win_chocolatey:
    name:
      - classic-shell
    state: present
    install_args: "ADDLOCAL=ClassicStartMenu"

- name: DetectionLab Menu
  win_shell: "\"C:\\Program Files\\Classic Shell\\ClassicStartMenu.exe -xml c:\\vagrant\\resources\\windows\\MenuSettings.xml\""



